### ISSUE TITLE
All my mocks got deleted

### ISSUE THREAD

**Issue by venkatgolla** [k32yr04n/amock#10]
Hey there,

Account details: Username - 	io.ui.automation@gmail.com
Member since - 17th Jan '17, 5:34

I was using amock.io since ~5 months. Everything was cool until today. I was quite surprised to see empty dashboard when I logged in to my account today. I was in an assumption that amock is free and I can use the mocks created anytime. But this is something new.

Also, I am unable to create new mocks. I'm seeing a message that says "Hold on..." for so long and nothing happens. Can you please suggest me a solution how to get my mocks back? This is a little important and urgent to me as of now.

Quick response is very much appreciated.

Cheers!!

**Comment by okkezie** [comment]
Hi venkatgolla,
Sorry for the inconveniences, Your mocks are not deleted. It was just a
temporary database connectivity issue which is now fixed. We are also
making necessary updates to ensure this does not happen again.
Please go ahead and login to the service and access your mocks. Mocks are
always free.

Thank you.
