### ISSUE TITLE
Could not able to find my mocks

### ISSUE THREAD

**Issue by santhosh-alluri** [k32yr04n/amock#11]
I have created a bunch of mocks and they use to work well. Today, all are disappeared suddenly on the dashboard  and could not able to create new mocks also. it's showing a message like "HOLD ON...". it's very important and urgent thing for me to get those mocks back to the dashboard. can any one suggest me, what is the solution?

**Comment by okkezie** [comment]
Hi Santhosh-alluri, Sorry for the inconveniences. The issue you experienced
was a temporary database connectivity issue which is now fixed. All your
mocks are still intact and not deleted. You can access them again from your
dashboard.

Thanks.

**Comment by santhosh-alluri** [comment]
Yeah. I can see them now... Thanks a lot k32yr04n.
