### ISSUE TITLE
Log My View Count

### ISSUE THREAD

**Issue by ionyekanna** [k32yr04n/amock#2]
Biko i want you to log the number of views to my endpoint

**Comment by okkezie** [comment]
Hi @zilpage 
The feature you requested have been implemented. Thanks for your feedback. See screenshot.

![mock](https://cloud.githubusercontent.com/assets/2904828/18015025/b0141d1c-6bbd-11e6-9a23-c76d118dc0a3.PNG)

**Comment by okkezie** [comment]
I'm closing this issue since it has been resolved. you can raise a new issue if you have more suggestions or spot a bug.
Thanks.
