### ISSUE TITLE
Ability to Edit Mock

### ISSUE THREAD

**Issue by Emmarock** [k32yr04n/amock#3]
while trying to access amock.io I observed that if a user create a mock, you can only delete the mock, you can't edit it.

**Comment by okkezie** [comment]
Thanks for your feedback @Emmarock. This feature will be included in the next updated coming shortly.

**Comment by okkezie** [comment]
Hi @Emmarock, I'm closing this issue because It's been resolved. See screenshot below. Please don't hesitate to log a new issue if you have more suggestions or spot any bug.
Thanks.

![edit-mock](https://cloud.githubusercontent.com/assets/2904828/18032350/45cf41a0-6cfa-11e6-9e8c-f48e0de91b12.PNG)
