### ISSUE TITLE
Assume application/json if no Content-Type specified

### ISSUE THREAD

**Issue by cdfwork** [k32yr04n/amock#5]
This is an awesome service, thanks for providing it!  As an enhancement request, it would be great if your server side code "defaulted" to application/json when the http request does not specify the content-type.  I'm using a Rest client with a bug that does not set the content-type and your service can't find a corresponding route if the content-type is not specified so I had to create my own app instead of using this service.  But thank you anyway!

**Comment by okkezie** [comment]
Thanks for your feedback. I'm currently working on implementing your suggestion. It will be in my next deployment.
