### ISSUE TITLE
End Point Formation on amock.io

### ISSUE THREAD

**Issue by olaolumusic** [k32yr04n/amock#7]
HI there, 
I created a couple of  endpoints and got an error (Resource already exists. No action taken.) but when I checked my dashboard, i couldn't find the End point in question, my thinking is that the app is checking the global url as oppose to the one linked to my account.

It wont be a bad idea to have 
http://www.amock.io/api/v1/username/new instead of
_http://www.amock.io/api/v1/new_
That way i'm sure that the username rule during creation would have prevented duplicate.

Regards.

**Comment by okkezie** [comment]
Hi @olaolumusic. This suggestion has been implemented and deployed. Thanks for your feedback. This issue is now closed.
