### ISSUE TITLE
Mock not getting persisted

### ISSUE THREAD

**Issue by ship2moon** [k32yr04n/amock#9]
The mock which I created was not getting saved!!! So no point in using this amock.io!

**Comment by okkezie** [comment]
Hi Longanathan, Is it possible that you are not signed in? Mocks you create
when you are not signed in are automatically deleted after 24 hours.

**Comment by ship2moon** [comment]
I've signed in. Leave it.. I found a better one

**Comment by okkezie** [comment]
The problem was linked to a recent database connection issue we had which
is now fixed. Sorry for the inconveniences. We really appreciate your
feedback.
